### ISSUE TITLE
Read获取到的数据格式和接收时解构赋值的格式不一致

### ISSUE THREAD

**Issue by tinfy** [zionLZH/osharp-vben-admin#1]
在 src\views\osharp\identity 路径下的 user.vue 文件中，Read(body) 方法获取到的数据格式为 {“Rows:”[...], "Total":2778}，和接收时解构赋值的数据格式不一致，其他的 vue 文件中也有同样的问题。
![code](https://user-images.githubusercontent.com/42999170/164130957-53dc11fc-1fb4-4924-ac72-1149894f0ed3.png)

**Comment by zionLZH** [comment]
这是因为OSharp官方在这些内置接口是直接回传数据，对于一部分公司而言会将其包装一层Data，这样有利于统一全局的请求解构，这几天我会处理一下，让其能兼容俩种方式

**Comment by zionLZH** [comment]
@tinfy 已解决 -> [链接地址](https://github.com/zionLZH/osharp-vben-admin/commit/26af9405ba49f10888088190b3ccd56eaa0b341d)
