### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by lurudong** [zionLZH/osharp-vben-admin#3]
登录后返回这个错误，是不是版本没有对上
![image](https://github.com/zionLZH/osharp-vben-admin/assets/44517714/285394da-9c00-41f5-a093-96dd7af4847e)

**Comment by zionLZH** [comment]
能否提供一下Token接口反馈的数据结构，这边来看看，一般来说这只是数据解析的问题

**Comment by zionLZH** [comment]
@lurudong 能否提供一下Token接口反馈的数据结构，这边来看看，一般来说这只是数据解析的问题

**Comment by lurudong** [comment]
@zionLZH 
![image](https://github.com/zionLZH/osharp-vben-admin/assets/44517714/0e515018-d052-4a23-ba0d-51f9126d2c34)

**Comment by zionLZH** [comment]
@lurudong 
提供接口返回的数据，或者是吧
```
if (data.Data.AccessToken) {
```
改成
```
if (data.Data && data.Data.AccessToken) {
```

**Comment by lurudong** [comment]
@zionLZH  
![image](https://github.com/zionLZH/osharp-vben-admin/assets/44517714/c8110643-efb6-4174-9b23-1290ecd871a6)
fanhui 返回是这样的。
我不知道只有这里是这样的，还是整个系统 都是这样。

**Comment by lurudong** [comment]
@zionLZH  
![image](https://github.com/zionLZH/osharp-vben-admin/assets/44517714/7feb9d0f-ffc8-46be-93e1-b7c72fbc2a26)
这个代码导致的，要改成osharp.Mvc?.IsLowercaseJsonProperty==true

**Comment by zionLZH** [comment]
那就是osharp配置的问题，改一下就行 @lurudong ，那这个我就设置close了
